import { resolve } from "node:path";
import { readdirSync, writeFileSync } from "node:fs";

const PROJECT_ROOT = resolve(import.meta.dir, "..");
const CHECKS_DIR = resolve(PROJECT_ROOT, "checks");
const OUTPUT_FILE = resolve(PROJECT_ROOT, "lib/generated/check-slugs.ts");

function parseCheckFilename(filename: string): { position: number; slug: string } {
  const match = filename.match(/^(\d+)-(.+)\.md$/);
  if (!match) {
    throw new Error(`Check filename must start with a numeric position: ${filename}`);
  }

  return {
    position: Number(match[1]),
    slug: match[2]!,
  };
}

const checks = readdirSync(CHECKS_DIR, { withFileTypes: true })
  .filter((e) => e.isFile() && e.name.endsWith(".md"))
  .map((e) => parseCheckFilename(e.name))
  .sort((a, b) => a.position - b.position);

const slugs = checks.map((check) => check.slug);

const unionMembers = slugs.map((s) => `  | "${s}"`).join("\n");

const output = `// Auto-generated by scripts/generate-check-slugs.ts — do not edit manually.
// Regenerate with: bun run generate

export const CHECK_SLUGS = [${slugs.map((s) => `"${s}"`).join(", ")}] as const;

export type CheckSlug =
${unionMembers};
`;

writeFileSync(OUTPUT_FILE, output);
console.log(`Wrote ${slugs.length} slugs to ${OUTPUT_FILE}`);
